action_selector: epsilon_greedy
additional_update: true
adv_hypernet_embed: 64
adv_hypernet_layers: 1
agent: rnn_fast
agent_output_type: q
atol_memory: 0.013
attend_reg_coef: 0.001
buffer_size: 5000
buffer_size_update: 5000
curiosity_decay: true
curiosity_decay_cycle: 100000
curiosity_decay_rate: 0.9
curiosity_decay_stop: 0.0
curiosity_scale: 0.001
delta_cover_type: 1
double_q: true
ec_buffer_embedder_update_interval: 10000
ec_buffer_stats_update_interval: 200
emb_out_type: 3
emb_training_batch: 204800
emb_training_mini_batch: 2048
emdqn_buffer_size: 1000000
emdqn_latent_dim: 4
emdqn_loss_weight: 0.1
encoder_type: 1
epsilon_anneal_time: 50000
epsilon_finish: 0.05
epsilon_start: 1.0
experiment_name: 5m_vs_6m
fixed_delta: true
flag_init_desirability: false
flag_memory_cnt_reset: false
flag_stats_norm: true
hypernet_embed: 64
individual_q_loss_weight: 0.01
is_adv_attention: true
is_minus_one: true
is_prioritized_buffer: false
is_stop_gradient: true
lambda_kl: 0.0001
lambda_s: 0.1
learner: qplex_curiosity_vdn_learner
mac: fast_mac
mask_dead: false
memory_emb_type: 1
mixer: dmaq_qatten
mixing_embed_dim: 32
n_head: 4
name: EMU_sc2
nonlinear: false
num_circle: 1
num_kernel: 4
optimality_incentive: true
optimality_type: 1
predict2_vdn_target: true
predict_vdn_target: true
rtol_memory: 0.0
runner: episode
save_buffer: false
soft_update_tau: 0.005
state_bias: true
t_EC_update: 0
target_update_interval: 200
use_AEM: true
use_emdqn: true
use_individual_Q: false
use_qtotal_td: false
vdn_soft_update: true
weighted_head: false
