# --- Qatten specific parameters ---

# Exploración - Ajuste de epsilon
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 100000  # ⬆️ Aumentado para evitar explotación prematura

runner: "episode"

buffer_size: 10000  # ⬆️ Aumentado para almacenar más experiencias útiles

# Frecuencia de actualización de la red objetivo
target_update_interval: 250  # ⬆️ Aumentado para estabilidad

# Aprendizaje por refuerzo
agent_output_type: "q"
learner: "qplex_curiosity_vdn_learner"
double_q: True
mixer: "dmaq_qatten"
mixing_embed_dim: 32
hypernet_embed: 64
adv_hypernet_layers: 1
adv_hypernet_embed: 64

num_kernel: 4
is_minus_one: True
is_adv_attention: True
is_stop_gradient: True

#.. EMU (Episodic Memory Unit) ---------------------------------

# Parámetros de memoria episódica
ec_buffer_stats_update_interval   : 200
ec_buffer_embedder_update_interval: 8000  # ⬇️ Disminuido para actualizaciones más frecuentes
emb_training_batch                : 102400  # ⬇️ Reducido para evitar sobreentrenamiento
emb_training_mini_batch           : 1024
t_EC_update                       : 0
buffer_size_update                : 10000  # ⬆️ Aumentado para más retención

rtol_memory  : 0.0        
atol_memory  : 0.00005  # ⬆️ Aumentado para ser más tolerante en la comparación de estados

# Variables de control
memory_emb_type     : 3
emb_out_type        : 3
encoder_type        : 1
use_AEM             : True
flag_stats_norm     : True
delta_cover_type    : 1
fixed_delta         : True
additional_update   : True
optimality_incentive: True
optimality_type     : 1
flag_memory_cnt_reset: False
flag_init_desirability: True  # ⬆️ Restaurado para mejorar la formación de conexiones en memoria episódica

# Hiperparámetros específicos de memory_emb_type==3
lambda_s         : 0.1
lambda_kl        : 0.0001

#--------------------------------------------------

# Coeficientes de Qatten
n_head: 4
attend_reg_coef: 0.001
state_bias: True
mask_dead: False
weighted_head: False
nonlinear: False

num_circle: 1

# Exploración por curiosidad
curiosity_scale: 0.005  # ⬆️ Aumentado para incentivar la exploración
curiosity_decay: True
curiosity_decay_rate: 0.95  # ⬆️ Menos decay para mantener curiosidad por más tiempo
curiosity_decay_cycle: 150000  # ⬆️ Más gradual
curiosity_decay_stop: 0.01  # ⬆️ Se mantiene incentivo bajo pero constante

save_buffer: False

mac: "fast_mac"
agent: "rnn_fast"
use_individual_Q: False
individual_q_loss_weight: 0.01

is_prioritized_buffer: False
use_emdqn: True
emdqn_loss_weight: 0.1

emdqn_buffer_size: 2000000  # ⬆️ Aumentado para permitir más almacenamiento sin saturación
emdqn_latent_dim: 4

soft_update_tau: 0.002  # ⬇️ Disminuido para hacer cambios más suaves en la red
vdn_soft_update: True
predict_vdn_target: True
predict2_vdn_target: True
use_qtotal_td: False
name: "EMU_sc2_optimized"
# --- Qatten specific parameters ---

# Exploración - Ajuste de epsilon
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 100000  # ⬆️ Aumentado para evitar explotación prematura

runner: "episode"

buffer_size: 10000  # ⬆️ Aumentado para almacenar más experiencias útiles

# Frecuencia de actualización de la red objetivo
target_update_interval: 250  # ⬆️ Aumentado para estabilidad

# Aprendizaje por refuerzo
agent_output_type: "q"
learner: "qplex_curiosity_vdn_learner"
double_q: True
mixer: "dmaq_qatten"
mixing_embed_dim: 32
hypernet_embed: 64
adv_hypernet_layers: 1
adv_hypernet_embed: 64

num_kernel: 4
is_minus_one: True
is_adv_attention: True
is_stop_gradient: True

#.. EMU (Episodic Memory Unit) ---------------------------------

# Parámetros de memoria episódica
ec_buffer_stats_update_interval   : 200
ec_buffer_embedder_update_interval: 8000  # ⬇️ Disminuido para actualizaciones más frecuentes
emb_training_batch                : 102400  # ⬇️ Reducido para evitar sobreentrenamiento
emb_training_mini_batch           : 1024
t_EC_update                       : 0
buffer_size_update                : 10000  # ⬆️ Aumentado para más retención

rtol_memory  : 0.0        
atol_memory  : 0.00005  # ⬆️ Aumentado para ser más tolerante en la comparación de estados

# Variables de control
memory_emb_type     : 3
emb_out_type        : 3
encoder_type        : 1
use_AEM             : True
flag_stats_norm     : True
delta_cover_type    : 1
fixed_delta         : True
additional_update   : True
optimality_incentive: True
optimality_type     : 1
flag_memory_cnt_reset: False
flag_init_desirability: True  # ⬆️ Restaurado para mejorar la formación de conexiones en memoria episódica

# Hiperparámetros específicos de memory_emb_type==3
lambda_s         : 0.1
lambda_kl        : 0.0001

#--------------------------------------------------

# Coeficientes de Qatten
n_head: 4
attend_reg_coef: 0.001
state_bias: True
mask_dead: False
weighted_head: False
nonlinear: False

num_circle: 1

# Exploración por curiosidad
curiosity_scale: 0.005  # ⬆️ Aumentado para incentivar la exploración
curiosity_decay: True
curiosity_decay_rate: 0.95  # ⬆️ Menos decay para mantener curiosidad por más tiempo
curiosity_decay_cycle: 150000  # ⬆️ Más gradual
curiosity_decay_stop: 0.01  # ⬆️ Se mantiene incentivo bajo pero constante

save_buffer: False

mac: "fast_mac"
agent: "rnn_fast"
use_individual_Q: False
individual_q_loss_weight: 0.01

is_prioritized_buffer: False
use_emdqn: True
emdqn_loss_weight: 0.1

emdqn_buffer_size: 2000000  # ⬆️ Aumentado para permitir más almacenamiento sin saturación
emdqn_latent_dim: 4

soft_update_tau: 0.002  # ⬇️ Disminuido para hacer cambios más suaves en la red
vdn_soft_update: True
predict_vdn_target: True
predict2_vdn_target: True
use_qtotal_td: False
name: "EMU_sc2_optimized"
